### ISSUE TITLE
Function Naming

### ISSUE THREAD

**Issue by AadiPatangi** [Awesomeplayer165/Ninety-nine-card-game#1]
screw this

**Comment by Awesomeplayer165** [comment]
Where have you learned coding????? When does it say shorter names are better. camel case and have it as long as I want (if i had to make a limit it would be like 50 char). Like we have autocomplete!

**Comment by AadiPatangi** [comment]
What I am saying is that say you hve a function that adds two number:
would I say:
def IAmAddingTwoNumbers:

**Comment by AadiPatangi** [comment]
I learned this in HarvardX
just a suggestion
